POST http://localhost:9000/auth/login
Content-Type: application/json

{"email":"bob@gmail222.com", "password":"d33333efaultPassword123"}



### ask server to decrypt and return our JWT
GET http://localhost:9000/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYzNzUyOSwiZW1haWwiOiJib2JAZ21haWwyMjIuY29tIiwicGFzc3dvcmQiOiJkMzMzMzNlZmF1bHRQYXNzd29yZDEyMyIsImlzTG9nZ2VkSW4iOnRydWUsImlhdCI6MTY1NzcxODU4MSwiZXhwIjoxNjU3NzIyMTgxfQ.DOJnK8XMcphgz8MCF0sussqOFHhyHLTFVinIvH5s-rI
